# Generated by Django 5.2.7 on 2025-10-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('order_created', 'Order Created'), ('order_status_changed', 'Order Status Changed'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('score_updated', 'Score Updated'), ('score_recomputed', 'Score Recomputed'), ('customer_login', 'Customer Login'), ('profile_viewed', 'Profile Viewed'), ('report_downloaded', 'Report Downloaded'), ('customer_created', 'Customer Created'), ('customer_updated', 'Customer Updated')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='profiles.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='profiles_ac_created_1debd8_idx'), models.Index(fields=['customer', '-created_at'], name='profiles_ac_custome_ab7eea_idx'), models.Index(fields=['action', '-created_at'], name='profiles_ac_action_d29a6a_idx'), models.Index(fields=['severity', '-created_at'], name='profiles_ac_severit_a05d8d_idx')],
            },
        ),
    ]
